version: 2.1

orbs:
  yarn: artsy/yarn@5.1.3
  codecov: codecov/codecov@1.2.5
  auto: artsy/auto@1.3.2

workflows:
  build_and_verify:
    jobs:
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - yarn/relay:
          requires:
            - yarn/workflow-queue
      - yarn/run:
          name: lint-changed
          script: lint-changed
          requires:
            - yarn/workflow-queue
      - yarn/type-check:
          requires:
            - yarn/workflow-queue
      - yarn/jest:
          args: --runInBand
          only_test_changed: true
          notify_slack_on_failure: true
          context: slack-reaction-test-failures
          requires:
            - yarn/workflow-queue
          post-steps:
            - codecov/upload:
              file: coverage/lcov.info
      - auto/publish-canary:
          context: npm-deploy
          filters:
            branches:
              ignore:
                - master
          requires:
            - yarn/jest
            - yarn/relay
            - lint-changed
            - yarn/type-check
            - yarn/update-cache
      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only:
                - master
          requires:
            - yarn/jest
            - yarn/relay
            - lint-changed
            - yarn/type-check
            - yarn/update-cache
